spring.application.name=CadastroDeFilmes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/cadastro_filmes
spring.datasource.username=postgres
spring.datasource.password=Tank2020